---
dart_sass:
    dest: local/externals/dart_sass
google_fonts:
    dest: static/externals/google_fonts
    fonts:
        'Open Sans':
            variants:
                - regular
                - italic
                - 700
                - 700italic
            subsets:
                - latin
                - latin-ext
            formats:
                - woff2
                - woff
                - ttf
    icons:
        types:
            - 'Material Icons'
            - 'Material Icons Outlined'
            - 'Material Icons Two Tone'
            - 'Material Icons Round'
            - 'Material Icons Sharp'
        formats:
            - woff2
            - woff
vue:
    dest: static/externals/vue
    libs:
        vue/dist/vue.global.js                   : vue.global.js
        vue/dist/vue.global.prod.js              : vue.global.prod.js
        vue-demi                                 : demi.iife.js
        pinia@2.3.1/dist/pinia.iife.js           : pinia.iife.js
        pinia@2.3.1/dist/pinia.iife.prod.js      : pinia.iife.prod.js
        vue-router/dist/vue-router.global.js     : vue-router.global.js
        vue-router/dist/vue-router.global.prod.js: vue-router.global.prod.js
font_awesome:
    dest : static/externals/font_awesome
    parts:
        - webfonts/*
        - css/all.css
        - css/all.min.css
