---
google_fonts:
    dest:
        fonts : static/fonts
        css   : config/assets/css/fonts
    fonts:
        Roboto:
            variants:
                'Roboto Regular' : regular
                'Roboto Italic'  : italic
                'Roboto Bold'    : 500
            subsets:
                - latin
                - latin-ext
            formats:
                - woff2
        'Open Sans':
            variants:
                'Open Sans Regular' : regular
                'Open Sans Italic'  : italic
                'Open Sans Bold'    : 700
            subsets:
                - latin
                - latin-ext
            formats:
                - woff2
    icons:
        browser: 'Firefox/104.1'
        types:
            - 'Material Icons'
            - 'Material Icons Outlined'
            - 'Material Icons Two Tone'
            - 'Material Icons Round'
            - 'Material Icons Sharp'
vue:
    dest: static/js/vue
    libs:
        unpkg.com/vue/dist/vue.global.js                    : vue.js
        unpkg.com/vue/dist/vue.global.prod.js               : vue.min.js
        unpkg.com/vuex/dist/vuex.global.js                  : vuex.js
        unpkg.com/vuex/dist/vuex.global.prod.js             : vuex.min.js
        unpkg.com/vue-router/dist/vue-router.global.js      : vue-router.js
        unpkg.com/vue-router/dist/vue-router.global.prod.js : vue-router.min.js
font_awesome:
    dest: static/font-awesome
    parts:
        - webfonts
        - css/all.css
        - css/all.min.css
