---
google_fonts:
    dest:
        fonts : static/fonts
        css   : config/assets/css/fonts
    fonts:
        Roboto:
            variants:
                - 'Roboto Normal' : regular
                - 'Roboto Italic' : italic
                - 'Roboto Bold'   : 500
            subsets:
                - latin
            formats:
                - woff2
vue:
    dest: static/js/vue
    libs:
        unpkg.com/vue        : vue.js
        unpkg.com/vuex       : vuex.js
        unpkg.com/vue-router : vue-router.js
font_awesome:
    dest: static/font-awesome
    parts:
        - webfonts
        - css/all.css
        - css/all.min.css
