---
google_fonts:
    dest:
        fonts : static/fonts
        css   : config/assets/css/fonts
    fonts:
        'Open Sans':
            variants:
                - regular
                - italic
                - 700
                - 700italic
            subsets:
                - latin
                - latin-ext
            formats:
                - woff2
                - woff
    icons:
        types:
            - 'Material Icons'
            - 'Material Icons Outlined'
            - 'Material Icons Two Tone'
            - 'Material Icons Round'
            - 'Material Icons Sharp'
        formats:
            - woff2
            - woff
vue:
    dest: static/js/vue
    libs:
        unpkg.com/vue/dist/vue.global.js                    : vue.js
        unpkg.com/vue/dist/vue.global.prod.js               : vue.min.js
        unpkg.com/vuex/dist/vuex.global.js                  : vuex.js
        unpkg.com/vuex/dist/vuex.global.prod.js             : vuex.min.js
        unpkg.com/vue-router/dist/vue-router.global.js      : vue-router.js
        unpkg.com/vue-router/dist/vue-router.global.prod.js : vue-router.min.js
font_awesome:
    dest: static/font-awesome
    parts:
        - webfonts
        - css/all.css
        - css/all.min.css
