---
google_fonts:
    dest:
        fonts : static/fonts
        css   : config/assets/css/fonts
    fonts:
        'Open Sans':
            variants:
                - regular
                - italic
                - 700
                - 700italic
            subsets:
                - latin
                - latin-ext
            formats:
                - woff2
                - woff
    icons:
        types:
            - 'Material Icons'
            - 'Material Icons Outlined'
            - 'Material Icons Two Tone'
            - 'Material Icons Round'
            - 'Material Icons Sharp'
        formats:
            - woff2
            - woff
vue:
    dest: static/js/vue/lib
    libs:
        vue/dist/vue.global.js                   : vue.global.js
        vue/dist/vue.global.prod.js              : vue.global.prod.js
        vue-demi                                 : demi.iife.js
        pinia/dist/pinia.iife.js                 : pinia.iife.js
        pinia/dist/pinia.iife.prod.js            : pinia.iife.prod.js
        vue-router/dist/vue-router.global.js     : vue-router.global.js
        vue-router/dist/vue-router.global.prod.js: vue-router.global.prod.js
font_awesome:
    dest: static/font-awesome
    parts:
        - webfonts
        - css/all.css
        - css/all.min.css
